Prior to the scheduled January 1999 introduction of the euro, polls indicate most European Union citizens are in favor of it and believe it will be successful.
However, only 20% feel well informed about upcoming changes.
The European Commission maintains that it will be introduced on schedule.
France supports the euro.
Zambia expects to benefit from it.
By 1996, euro design development begins.
Britain's mortgage lenders prepare for euro mortgages.
In 1997, the code "EUR" is ascribed to the euro.
Few German companies have prepared for the transition.
By 1998, Germany's Bundesbank announces that private investors will benefit from it.
