The euro was scheduled to be used in cashless trading as of January 1, 1999, but the actual currency would not go into use until January 1, 2002, with present currencies' ceasing to be legal tender six months later.
A strong indication of financial markets' acceptance of the euro was the announcement by two banks that they would quote prices in euro seven months before its official adoption.
Reaction to the introduction of the euro was positive worldwide.
China welcomed the move.
Bulgaria worked to tie its currency to the euro and Thailand considered using it in its foreign reserves.
