In 1990 the National League for Democracy lead by Nobel Peace Prize winner Aung San Suu Kyi won an 82% parliamentary majority in Myanmar (formerly Burma).
The military State Law and Order Restoration Council that seized power in 1988 and commits widespread ethnic cleansing and rape, has for 8 years prevented Parliament from convening.
In January 1997 Suu Kyi was attacked and besieged in her van for 9 days by government-controlled thugs, to prevent her meeting elected lawmakers.
By September 1998 the SLORC had arrested nearly 200 lawmakers to prevent Parliament convening by or after NLD's Aug 21, 1998 deadline.
