Aung San won Burma's freedom from British rule in 1947 and was assassinated.
The military took over in 1962, then the State Law and Order Restoration Council (SLORC) in 1988, massacring thousands and renaming Burma "Myanmar".
The government continually harassed Aung San's daughter Suu Kyi who headed the opposition.
She wrote the essay "Freedom From Fear" and won the 1991 Nobel Peace Prize.
The National League for Democracy (NLD) party won 82 percent of the 1990 vote but the military annulled the election.
Suu Kyi set Aug 21, 1998 for convening the National Assembly.
The government made 900 political arrests.
