The UN committee report raised the prospect of Kakadu being placed on the committee's endangered list.
After intense lobbying efforts from the Australian government not to put the park on the endangered list, the committee instead ordered Australian authorities to provide a report detailing what is being done to prevent damage to the park.
Australian Environment Minister Robert Hill attacked the UN report, describing is as biased and containing errors of science.
He said the mine would go ahead anyway.
The UN committee defended the report, saying its recommendations were designed to remove real and potential dangers to Kakadu.
