In 1998 antitrust settlement talks delayed shipment of Windows 98.
Microsoft was allowed to integrate its internet browser into Windows.
The US Department of Justice and 19 states began trial against Microsoft for antitrust practices.
In November 1998 a California court issued a preliminary injunction to stop Microsoft violating its JAVA license with Sun Microsystems or stop shipping JAVA products.
Japan's Fair Trade Commission told Microsoft to permanently stop bundling EXCEL and WORD to computer makers.
In 1999 the US antitrust suit claimed Microsoft illegally coerced IBM to "eliminate or drop" its OS/2 else pay higher than market Windows prices.
