Matthew Shepard, a gay 21-year old student at the University of Wyoming was kidnapped, savagely bludgeoned and left lashed to a fence in freezing weather.
He was found 18 hours later and rushed to a hospital in Colorado where he died a week later.
This heinous event inspired vigils and demonstrations all around the country.
Also, during this period many conservative religious were disparaging gays and the gay lifestyle.
One of the two men who committed the act, Russell Henderson, pled guilty and was sentenced to two consecutive life terms, leaving no hope for parole.
