Former Speaker Newt Gingrich has filed for divorce from his wife, Marianne, after 18 years of marriage.
This is his second marriage; the first also ended in divorce.
In a counterclaim to the divorce petition, Marianne accused Gingrich of transferring valuable assets before filing and asked the judge to stop any further transfers.
Gingrich asked a judge to settle his divorce by relying on a financial agreement that he and Marianne worked out during a six year separation several years earlier.
Marianne has asked to depose Callista Bisek, a congressional clerk with whom Gingrich has been having an affair.
