Speaker of the House Newt Gingrich resigned from his House seat effective January 6, 1999.
In July, he filed for a divorce from his wife Marianne.
This prompted a series of claims and counterclaims between the two about each other's assets and personal affairs.
Mrs. Gingrich served notice to depose a number of her husband's close friends and advisors, and Callista Bisek, a congressional aide with whom he had been having an affair for several years.
Ms. Bisek filed a request to overturn any requests for her to answer questions.
The Gingriches reached agreement on dividing their assets in September.
