Vice President Al Gore officially opened his campaign headquarters in Nashville.
He said that campaign chairman Tony Coelho would stay in place despite some past questionable financial management.
Seven months later, however, Coelho would leave the campaign for health reasons.
Commerce Secretary William Dailey then became campaign chairman.
Donna Brazile was promoted to campaign manager.
As former Senator Bill Bradley appeared to be gaining on Gore in the polls and in fund raising, Gore sought and received the endorsement of Senator Ted Kennedy.
Gore selected Connecticut Senator Joseph Lieberman to be his running mate.
