Matthew Shepard, a gay University of Wyoming student, died after being in a coma for five days.
He had been robbed, beaten, and left to die on a fence outside of Laramie, Wyoming.
Two suspects, Aaron McKinney and Russell Henderson, were ordered to stand trial on first-degree murder charges.
Henderson pleaded guilty and was sentenced to two life terms.
McKinney went to trial.
The murder galvanized national outrage over anti-homosexual violence.
There were candlelight vigils across the country and a march in New York.
Religious right leaders, while deploring violence towards gays, insisted they hated the sin, not the sinner.
