The trial of Aaron McKinney, the second man accused of murdering gay University of Wyoming student Matthew Shepard, opened in Laramie.
The other man, Russell Henderson was sentenced to two consecutive life terms.
Prosecutors showed the jury pictures of the victim and crime scene.
McKinney's defense team hoping to save him from the death penalty, conceded that he was guilty of manslaughter.
They argued he had been an earlier victim of sexual abuse and on the night of the attack was affected by alcohol and methamphetamines.
Shepard's murder prompted over 450 bills on issues important to gays in state legislatures.
