In June 1999, California's Assembly added disability, gender and sexual orientation to hate crime law, extending the maximum murder sentence to life, not death.
More than 450 bills were introduced nation-wide on gay and lesbian issues.
At McKinney's trial in October, McKinney's attorney pleaded that McKinney committed manslaughter in five minutes of "gay panic" to a sexual advance from Shepard, because drug and alcohol addicted McKinney had been abused homosexually at age 7 and had consensual homosexual sex at 15.
The prosecution sought a first-degree murder death penalty arguing McKinney fully intended to murder Shepard after kidnapping and robbing him.
