Gore continued his effort to rally women to his campaign and to add women to prominent positions on his campaign team.
He received endorsements from Rep. Patrick Kennedy, from California congressional leaders, including Sen. Dianne Feinstein, and from Latino leaders.
An influential environmental group endorsed former Sen. Bradley, Gore's sole competitor for the Democratic nomination.
The Gore campaign conducted a fund-raiser aimed at gays, raising more than $150,000.
In September, Gore announced that he was moving his campaign headquarters to Tennessee.
The move, expected to cut expenses, was seen as an effort by Gore to distance himself from President Clinton.
