Newt Gingrich separated from his wife Marianne in May 1999 and filed for divorce on July 29.
Marianne claimed he transferred assets prior to seeking a divorce.
She sought to depose Callista Bisek, Newt's alleged mistress, and four of his business/political associates.
The couple had been separated previously for six years.
They signed a financial agreement and reconciled in 1993.
Newt asked the judge to settle the divorce based on that agreement.
The couple sought to keep their private lives out of the public view.
They reached a confidential agreement on how to divide their finances during the separation.
