Oprah Winfrey is the richest and most influential woman in entertainment.
Her TV talk show continues its top ratings success since its launching in September 1986, winning 32 daytime Emmys.
She has been successful in promoting books, including having their authors on her show, and making TV movie versions of some of the novels.
Recently she has been presenting a "change your life" theme focusing on who you are, and a truth-will-set-you-free attitude, influenced by her own traumatic childhood.
A free over-the-tube seminar will be given by "change your life" guru John Gray.
She remains a proponent of inspirational reading.
