Being chosen for Oprah's Book Club, founded in 1996, almost guarantees that a book will be a best seller.
Oprah chose North Carolina novelist Robert Morgan for a book club discussion.
His book "Gap Creek" is set in turn-of-the-century Appalachia and deals with premature births and deaths, malnutrition, poverty and other hardships.
The appearance of talk shows and Oprah's taking her Chicago-based talk show national are among television's top moments.
A federal court ruled that The Oprah Winfrey show "melodramatized" the mad cow disease scare but did not give false information about it or defame cattle producers.
