Oprah Winfrey announced that she is developing a TV channel named Oxygen, and starting a magazine to inform and inspire women.
Her book club promotions on TV won her a 50th Anniversary medal from the National Book Foundation.
The latest book club discussion was about the novel, Gap Creek.
The federal appeals court in New Orleans ruled that the Oprah Winfrey show "melodramatized" the mad cow disease scare but didn't give false information or defame cattle producers.
Oprah received praise for teaching a class at Northwestern University, but her show ranking dropped slightly after a below- expectations performance in "Beloved."
