A 7.4 Richter earthquake hit Izmit Turkey at 0300 GMT August 17, 1999; 5 Richter and 4 Richter aftershocks followed.
Nineteen countries sent over 1,000 rescuers.
Turkey's own rescue efforts were ineffectual.
Official estimates were: 12,018 dead, 45,000 missing, 10,000 trapped, 33,515 under medical treatment beyond thousands treated earlier.
Worst affected were Izmit: 4,179 dead, 10,759 injured; Adapazari 3,046 dead, 6,884 injured; and Yalova 2,400 dead, 5,559 injured.
Economic loss was $20 billion, including the Izmit Oil Refinery fire, pollution, gas and oil shortages.
The Golcuk naval base was destroyed.
Power and communications were down from Ankara to northwest Turkey.
