There were 1300 aftershocks in the region including an earthquake measuring 5.0.
The survivors continued to suffer as heavy rains battered the region.
There was a shortage of shelters and fear of a typhoid epidemic.
Hospitals continued to be flooded with victims and field hospitals were working where hospitals had been destroyed or damaged.
Early estimates of economic loss were between $20 and 40 billion.
The quake's enormous social and economic impact continued to grow with factories idle and 9 of the 30 oil refinery tanks damaged by the fire.
The government struggled for money to repair basic infrastructure.
