After departing Switzerland on March 1, 1999, a Swiss/British balloon team drifted southwestward to North Africa before catching a favorable jet stream at 9.27 degrees west longitude.
From there the team flew east across Asia, then over the Pacific for six days to Mexico.
Leaving Mexico, the team floated over Central America, crossed the Caribbean towards Jamaica, and steered towards the "finish line" somewhere along longitude 9.27 degrees west in Mauritania, North Africa.
On their 18th day aloft, the balloonists began crossing the Atlantic on the last leg of what was expected to be a successful, non-stop, around-the-world balloon flight.
