A massive earthquake measuring 7.4 on the Richter scale hit western Turkey at 3:00 am local time on August 17, 1999.
The epicenter was near the industrial city of Izmit, about 70 kilometers southeast of Istanbul.
Relief workers, money, and rescue equipment poured in from around the world.
The casualties included more than 12,000 dead, up to 35,000 missing, and thousands injured.
The destruction was tremendous, with water pipes broken, electric lines down, roads impassible, and a fear of disease.
An oil refinery fire was finally taken under control by August 21 with the help of foreign rescue workers.
