Myanmar's military regime continues its campaign against Suu Kyi's opposition political party, the National League for Democracy.
The NLD claimed the military arrested 702 of its members since 1998 and threatened to arrest its vice-chairman, Tin Oo, on parole violation charges.
Exiled dissidents in Thailand and Bangladesh protested on the tenth anniversary of the military takeover of Burma.
The military regime continues to rebuff repeated appeals for talks with the democratic opposition.
The regime has been accused of drug trafficking and widespread human rights violations.
The US and Europe boycotted an international heroin conference in Myanmar for these reasons.
