In 1998 the SLORC threatened 71-year old Tin Oo, NLD Vice Chairman, who in 1974 ordered troops not to fire on unarmed students, with re-imprisonment for continued political activities "violating" his 1995 parole.
In the World Trade Organization Europe and Japan challenged a 1996 US law banning government agencies from trading with anyone who trades with Myanmar.
British officials were banned from entering Myanmar after pressuring the SLORC to meet with Suu Kyi.
The EU restricted arms and non-humanitarian aid to Myanmar.
The US and EU countries boycotted an international heroin conference in Myanmar, "the world's leading source of heroin."
