Tin Oo, 1998 NLD vice-chairman, fought with Aung San for independence.
In 1974 he refused to order troops to fire on demonstrators, thus angering dictator Ne Win.
He was imprisoned twice and placed under house arrest in 1989.
Most foreign aid ended after 1988.
In 1996 Massachusetts banned state contracts with anyone trading with Burma.
A trade group sued and the law was disallowed in 1999.
Other US localities passed similar laws.
The US and others banned Burmese trade and investment and boycotted a heroin conference in Myanmar.
Swedish telecommunications giant Ericsson ended Burmese operations when threatened with a boycott.
