Myanmar has been ruled by the military in various guises since 1962.
After crushing a nationwide democracy movement, the State Law and Order Restoration Council took over Burma in 1998 and changed its name to Myanmar.
Nobel laureate Aung San Suu Kyi heads the popular opposition to the military government, which continues to harass and imprison members of her political party, anti-government ethnic armed groups, and student organizations.
The government has used forced labor and torture in carrying out its war against resistance by ethnic minorities.
Military bungling has turned resource-rich Myanmar to one of the world's poorest countries.
