The founding euro countries are Belgium, Germany, Spain, France, Ireland, Italy, Luxembourg, the Netherlands, Austria, Portugal and Finland.
The euro becomes a currency on January 1, 1999 for cashless trading.
Mass printing of euro notes begins in 1999.
They become legal tender on January 1, 2002.
Signs of the euro's acceptance include: two international banks quote prices in the euro; China welcomes its initiation; Eurostat offers euro-related information online; Bulgaria moves to link its currency with the euro; and Thailand considers using it in foreign reserves.
However, the European Central Bank announces it won't encourage its use as reserve currency.
