Since they seized power in 1988, Myanmar's military rulers have used forced labor, torture and rape to maintain power.
General Tin Oo is a top general in the regime.
Officially, 15 anti-government groups surrendered as of January 1998.
The NLD party, led by Suu Kyi, won the 1990 elections, but the junta won't honor election results.
Nobel Peace laureate Suu Kyi demanded that parliament be permitted to convene and protested for the release of political prisoners.
Estimated 500-900 political arrests occurred in the months preceding the tenth anniversary of the takeover, including members of the ABSDF, led by Ko Thein.
