In 2000 the US denied Burma anti-drug certification.
Refugees, heroin and methamphetamine, and HIV cross the border into Thailand.
The US has accepted hundreds of Burmese students from refugee camps in Thailand, which Myanmar claims are sites of terrorist training.
In October 1999 anti-government guerrillas held the Myanmar embassy in Bangkok hostage.
The siege ended peacefully after 25 hours.
The men were flown to the Myanmar border.
Burmese guerrillas stormed a Thai hospital in January 2000.
Dublin awarded the Freedom of the City honor to Suu Kyi in 2000.
Her son Kim Aris flew to Ireland to accept the award.
