Protests continued against the Jabiluka uranium mine.
A dozen protesters chained themselves together to block the entrance to the mine.
The Darwin office of Energy Resources of Australia LTD.
, owners and operators of the mine, was firebombed.
Rowdy protestors were ejected from the annual general meeting of ERA after interrupting the chairman's address.
A high-level UN committee investigated claims that the Jabiluka mine posed a threat to the cultural and environmental values of the Kakadu National Park.
The committee demanded that the mine be scrapped to prevent it from endangering the surrounding park and threatening Aboriginal archeological sites.
