In 1996, Energy Resources Australia requested approval for the Jabiluka uranium mine on the edge of the Kakadu National Park in the Northern Territory.
ERA's second uranium mine in the Kakadu World Heritage Area would generate billions of US dollars in revenue and create 2,000 jobs.
Opposition parties, conservationists and Aboriginal land owners opposed the planned mine.
However, studies found no adverse impact from ERA's other mine in the area.
After a protracted legal battle and amid continuing protests, ERA received approval and began mine construction in June 1998.
Police reported about 350 arrests as protesters attempted to block construction.
