In a 1994 Justice Department settlement Microsoft changed some licensing practices with computer makers.
In 1995 Justice blocked Microsoft's acquisition of Intuit.
In 1999 antitrust Judge Jackson issued "findings of fact" that Microsoft was a monopoly that abused its power.
Microsoft was still defending a case by Sun for violation of JAVA licenses and a case by Caldera for market power abuse.
In 2000 legal analysis in a third-party brief to Jackson foreshadowed a possible antitrust ruling.
Antitrust court mediated settlement talks collapsed with little time left before Jackson would issue his "findings of law" and verdict in March.
