Protests against the Jabiluka uranium mine continue.
Protesters have blockaded the site, firebombed an ERA office, and one threatened to blow himself up.
Rowdy protesters infiltrated ERA's annual general meeting.
ERA insists the mine won't adversely affect the Kakadu National Park.
The mine is supported by the current conservative government.
Opposition parties vow to halt construction if they win upcoming elections.
A UN World Heritage Bureau delegation's report recommended the proposed mine be stopped, claiming it would pose severe danger to the cultural and natural values of the adjacent park.
The Environmental Minister denounced the report as biased and unsubstantiated.
