Newt Gingrich has taken a more aggressive stance in divorce proceedings against his wife, Marianne.
He alleges that she has violated the agreement that each put his/her money into a joint account managed by an independent accountant.
That agreement also gives Marianne possession of the couple's house in Marietta and Newt gets the couple's Washington apartment.
Gingrich and Callista Bisek have admitted to a six-year affair.
Despite that admission, Marianne wants to depose Callista.
Newt wants to depose Marianne on the money question.
In a surprise move, Newt wants to depose Callista to show she is not under his control.
