Aaron McKinney's murder trial began in October 1998, close to the one-year anniversary of Matthew Shepard's death.
Prosecutor Cal Rerucha claimed that McKinney, and his friend Russell Henderson intended to murder Shepard after kidnapping and robbing him.
Jason Tangeman, one of McKinney's defense lawyers, conceded that McKinney was responsible for Shepard's death.
A coroner testified that Shepard's skull was fractured six times.
In attempting to get his client a life sentence rather than the death penalty, he argued that McKinney's past, which included sexual abuse as a child, caused him to lash out in rage at Shepard's sexual advances.
