In December 1998 Al Gore notified the Federal Election Commission that he had formed a campaign organization, thereby skipping creation of an exploratory committee.
Gore selected men for his campaign manager and four key positions.
Criticized for lack of women in his inner circle, he chose women as director of strategic operation and political director.
Gore has enormous amounts of money resulting from his speaking around the country and some key early endorsements.
Gore planned to gradually highlight differences with Clinton Policies and programs.
His campaign would focus on what his administration would do, not what Clinton's administration did.
