Vice President Al Gore will officially announce his candidacy for President on June 16th in Carthage, Tennessee.
Gore has endorsements from several quarters, including Congressman Patrick Kennedy and several Latino leaders.
Many California congressmen and both senators, Diane Feinstein and Barbara Boxer have endorsed Gore.
Campaign general chairman Tony Coelho announced that Kiki Moore will become press secretary.
Chief of staff Ron Klain is leaving the campaign and rumors indicate a rift between him and Coelho, but Klain said Coelho asked him to stay.
Gore decided to move his campaign headquarters from Washington to Nashville and to reduce his staff.
