Oprah Winfrey's TV show continues to garner Emmy nominations.
When an author, such as Wally Lamb, appears on her show to promote his book, it is almost certain to put it on the best-seller list.
Oprah has played a big part in the emergence of the tell-all culture on national TV.
Her show is all about learning who YOU are.
On one show, Oprah had an audience member take a stick and beat on a box labeled "guilt".
Oprah took her show to the Bahamas where the lineup included a "Sexiest Island Man" contest and bathing suit makeovers.
