The Oprah Winfrey Show features talking cures and learning who you are.
She includes a Wednesday seminar with "change your life" guru John Gray, who once handed an audience member a stick and told her to whack a box labeled "Guilt".
A stream of guests confesses their problems.
Oprah shared revelations of her sexually abused girlhood.
Oprah has been shown lounging in a bathtub surrounded by candles.
Author Wally Lamb appeared on Oprah's show and soon after his book topped the bestseller lists.
Shows broadcast from the Bahamas included a "Sexiest Island Man" contest and bathing suit makeovers.
