Talk show host Oprah Winfrey received a 50th Anniversary Medal from the National Book Foundation.
She is a powerful figure in the book world because of Oprah's Book Club.
However, Oprah was replaced as the most powerful woman in the entertainment business and dropped all the way to 19th.
The federal appeals court in New Orleans ruled that "The Oprah Winfrey" show "melodramatized" the mad cow disease scare but did not give false information and did not defame cattle producers.
