Bertrand Piccard from Switzerland wanted to be the first to circumnavigate the world non-stop in a balloon.
So far he has made three attempts, taking off from a mountain in the Swiss Alps near Lake Geneva with different crewmembers.
On his first attempt the balloon landed in the Mediterranean some six hours after take-off because of a fuel leak.
On the second attempt he landed in Myanmar when China refused to allow entrance into Chinese air space.
March 1999 found him on his third attempt picking up altitude and speed over the Sahara after chipping off icicles.
