Two nearly simultaneous earthquakes, measuring 7.4 on the Richter scale, struck in the Izmit region southeast of Istanbul early in the morning of 17 August 1999.
The quakes, followed by 27 aftershocks, did extensive damage.
Latest reports indicate extensive damage with over 10,000 deaths, 45,000 injured and over 10,000 trapped in damaged buildings and houses.
The shocks have damaged bridges, highways, power stations, telephone lines and also triggered a large fire at the Izmit Refinery.
Foreign rescue teams from around the world are assisting in providing aid and rescue operations.
The earthquake may account for $20 billion in economic loss.
