The third attempt had started on March 1, when Piccard and British teammate Brian Jones flew southwestward from the Geneva area before catching a favorable jet stream and heading eastward around the world.
They gained vital time by obtaining flight permission from China before taking off.
By March 17, after six days spent crossing the Pacific, they were over Belize and headed for Jamaica and the Dominican Republic.
The pilots were worried that they might not have enough fuel to reach the finish line, but by March 19 they were more than halfway across the Atlantic with favorable winds.
