After weeks of delays, Piccard and British Brian Jones set off from Switzerland on March 1, 1999.
They drifted down to North Africa and then crossed toward Asia.
Having gotten permission before their departure, they passed over southern China.
A jet stream whisked them over the Pacific Ocean before grinding to a near halt over Central America.
They finally picked up another jet stream Thursday, and Friday they beat the endurance record set just two weeks prior.
The balloonists were elated upon learning they had enough fuel to reach the finish line, 9 degrees longitude, in Africa by midday Saturday.
