The two consecutive earthquakes that struck Turkey about 3:00 am on 17 August 1999 lasted 45 seconds.
The epicenter of the tremors was near Izmit, east of Istanbul.
The death toll has surpassed 12,000 and 33,405 others are reported injured.
The economic loss is estimated at $20 to $40 billion.
Idle damaged factories may cause a loss of $300 million.
Cash is needed to repair the basic infrastructure, and the area hit provides almost half the tax revenue.
Some 200,000 homeless survivors are desperate for refuge.
The United States and Holland plan to send in prefabricated shelters and all-weather tents.
