Swiss balloonist Bertand Piccard abandoned his first attempt to circumnavigate the world non-stop in a balloon six hours after take-off because of a fuel leak, January 12, 1997.
For his second attempt, Piccard departed Switzerland January 28, 1998.
He planned to drift toward Italy, Greece and the Middle East and ride jet streams east-bound from there, completing the adventure in 10-20 days.
Piccard abandoned this attempt when China refused him entry, causing him to miss needed winds.
His third attempt was delayed by difficulties getting fly-over permission from China.
On March 5, 1999 Piccard was sailing over Africa's Sahara Desert.
