On January 12, 1997, a Swiss/Belgian team took off from the Swiss Alps in a bid to balloon non-stop around the world.
Expecting to travel for about two weeks, the two men aborted their attempt six hours after takeoff due to a hazardous fuel leak.
About a year later, the team (now also including an Englishman) resumed the quest but had to abandon their journey as China refused them entry into its airspace.
By late December of 1998, a revamped Swiss/British team, with conditional permission from China to fly over its terrain, prepared for a third attempt at the feat.
